### ISSUE TITLE
Calling php artisan opcache:clear recently throws the following error. Please help!

### ISSUE THREAD

**Issue by DasTippspiel** [michelecurletta/laravel-opcache-clear#2]
`Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 3 passed to GuzzleHttp\Client::request() must be of the type array, string given, called 
in /var/www/app/shared/vendor/guzzlehttp/guzzle/src/Client.php on line 87 in /var/www/app/shared/vendor/guzzlehttp/guzzle/src/Client.php:126
Stack trace:
#0 /var/www/domain/shared/vendor/guzzlehttp/guzzle/src/Client.php(87): GuzzleHttp\Client->request('createRequest', 'GET', 'http://app...')
#1 /var/www/app/releases/1477315172/app/Console/Commands/OpCacheClearCommand.php(38): GuzzleHttp\Client->__call('createRequest', Array)
#2 [internal function]: App\Console\Commands\OpcacheClearCommand->handle()
#3 /var/www/app/shared/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#4 /var/www/app/shared/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array)
#5 /var/www/app/shared/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/app/shared/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/app/shared/vendor/symfony/console/Application.php(844): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/app/shared/vendor/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\OpcacheClearCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/app/shared/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/app/shared/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/app/releases/1477593433/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 {main}`

**Comment by michelecurletta** [comment]
What version of Guzzle are you using?

**Comment by DasTippspiel** [comment]
I'm using "guzzlehttp/guzzle": "~6.0",

**Comment by michelecurletta** [comment]
Yeah, the problem is the version of guzzle are you using.
As you can see into the composer file, the package uses "guzzlehttp/guzzle": "5.3.*"

**Comment by michelecurletta** [comment]
@DasTippspiel if you want to fix the guzzle version used by package, I'd accept a PR to upgrade it.
